<a href="https://colab.research.google.com/github/abhayratti/exoplanet-detection/blob/main/Exoplanet_Detection_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [24]:
pd.set_option('display.max_columns', 50)

data = pd.read_csv('/content/cumulative.csv')
data.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,koi_impact,koi_impact_err1,koi_impact_err2,koi_duration,koi_duration_err1,koi_duration_err2,koi_depth,koi_depth_err1,koi_depth_err2,koi_prad,koi_prad_err1,koi_prad_err2,koi_teq,koi_teq_err1,koi_teq_err2,koi_insol,koi_insol_err1,koi_insol_err2,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_steff_err1,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,-0.002160,0.146,0.318,-0.146,2.95750,0.08190,-0.08190,615.8,19.5,-19.5,2.26,0.26,-0.15,793.0,NaN,NaN,93.59,29.45,-16.65,35.8,1.0,q1_q17_dr25_tce,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,-0.003520,0.586,0.059,-0.443,4.50700,0.11600,-0.11600,874.8,35.5,-35.5,2.83,0.32,-0.19,443.0,NaN,NaN,9.11,2.87,-1.62,25.8,2.0,q1_q17_dr25_tce,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,-0.000581,0.969,5.126,-0.077,1.78220,0.03410,-0.03410,10829.0,171.0,-171.0,14.60,3.92,-1.31,638.0,NaN,NaN,39.30,31.04,-10.49,76.3,1.0,q1_q17_dr25_tce,5853.0,158.0,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,1.276,0.115,-0.092,2.40641,0.00537,-0.00537,8079.2,12.8,-12.8,33.46,8.50,-2.83,1395.0,NaN,NaN,891.96,668.95,-230.35,505.6,1.0,q1_q17_dr25_tce,5805.0,157.0,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,-0.001130,0.701,0.235,-0.478,1.65450,0.04200,-0.04200,603.3,16.9,-16.9,2.75,0.88,-0.35,1406.0,NaN,NaN,926.16,874.33,-314.24,40.9,1.0,q1_q17_dr25_tce,6031.0,169.0,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [25]:
unrelated_features = ['rowid', 'kepid', 'kepoi_name', 
                       'kepler_name', 'koi_disposition', 'koi_insol', 
                       'koi_insol_err1', 'koi_insol_err2', 'koi_slogg', 
                       'koi_slogg_err1', 'koi_slogg_err2', 'koi_fpflag_ec',
                      'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_tce_delivname']
data = data.drop(unrelated_features, axis=1)

In [26]:
data = data.dropna()

In [27]:
from sklearn import preprocessing

In [28]:
le = preprocessing.LabelEncoder()

In [29]:
data['koi_pdisposition'] = le.fit_transform(data['koi_pdisposition'])

In [30]:
data_features = data.drop(['koi_pdisposition'], axis=1)

data_features.head()

,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,koi_impact,koi_impact_err1,koi_impact_err2,koi_duration,koi_duration_err1,koi_duration_err2,koi_depth,koi_depth_err1,koi_depth_err2,koi_prad,koi_prad_err1,koi_prad_err2,koi_model_snr,koi_tce_plnt_num,koi_steff,koi_steff_err1,koi_steff_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1.000,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,-0.002160,0.146,0.318,-0.146,2.95750,0.08190,-0.08190,615.8,19.5,-19.5,2.26,0.26,-0.15,35.8,1.0,5455.0,81.0,-81.0,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,0.969,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,-0.003520,0.586,0.059,-0.443,4.50700,0.11600,-0.11600,874.8,35.5,-35.5,2.83,0.32,-0.19,25.8,2.0,5455.0,81.0,-81.0,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,0.000,0,1,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,-0.000581,0.969,5.126,-0.077,1.78220,0.03410,-0.03410,10829.0,171.0,-171.0,14.60,3.92,-1.31,76.3,1.0,5853.0,158.0,-176.0,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,0.000,0,1,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,1.276,0.115,-0.092,2.40641,0.00537,-0.00537,8079.2,12.8,-12.8,33.46,8.50,-2.83,505.6,1.0,5805.0,157.0,-174.0,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,1.000,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,-0.001130,0.701,0.235,-0.478,1.65450,0.04200,-0.04200,603.3,16.9,-16.9,2.75,0.88,-0.35,40.9,1.0,6031.0,169.0,-211.0,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [31]:
data_target = data[['koi_pdisposition']]

In [32]:
from sklearn.model_selection import train_test_split
import torch 
from torch.utils.data import DataLoader, TensorDataset
import numpy as np

In [33]:
x_train, x_test, y_train, y_test = train_test_split(data_features, 
                                                    data_target, 
                                                    test_size=0.2, 
                                                    random_state=0)

In [34]:
x_train = torch.from_numpy(x_train.values).float()
x_test = torch.from_numpy(x_test.values).float()

y_train = torch.from_numpy(y_train.values).view(1,-1)[0]
y_test = torch.from_numpy(y_test.values).view(1,-1)[0]

In [35]:
import torch.nn as nn
import torch.nn.functional as F

In [36]:
x_train.shape, y_train.shape

(torch.Size([6242, 33]), torch.Size([6242]))

In [37]:
input_size = 33
output_size = 2
hid1_size = 25
hid2_size = 10

In [38]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(input_size, hid1_size)
    self.fc2 = nn.Linear(hid1_size, hid2_size)
    self.fc3 = nn.Linear(hid2_size, output_size)
  
  def forward(self, x):
    x = F.sigmoid(self.fc1(x))
    x = F.sigmoid(self.fc2(x))
    x = self.fc3(x)

    return F.log_softmax(x, dim=-1)

In [39]:
model = Net()

In [40]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters())

loss_fn = nn.NLLLoss()

In [41]:
epochs = 1001

In [49]:
for epoch in range(1, epochs):
  optimizer.zero_grad()

  output_train = model(x_train)

  loss = loss_fn(output_train, y_train)
  loss.backward()

  optimizer.step()

  # testing data
  output_test = model(x_test)
  loss_test = loss_fn(output_test, y_test)

  _, pred = output_test.data.max(1)

  # accuracy
  accuracy = torch.sum(pred == y_test.data).item() / y_test.size(0)

  if epoch % 50 == 0:
    print (f'epoch: {epoch} || train loss: {loss} || test loss: {loss_test} || accuracy: {accuracy}')

epoch: 50 || train loss: 0.15315647423267365 || test loss: 0.14404267072677612 || accuracy: 0.9628443305573351
epoch: 100 || train loss: 0.12857767939567566 || test loss: 0.12161324173212051 || accuracy: 0.9666880204996797
epoch: 150 || train loss: 0.1170097216963768 || test loss: 0.14645156264305115 || accuracy: 0.9660474055092889
epoch: 200 || train loss: 0.08938217163085938 || test loss: 0.08456077426671982 || accuracy: 0.9782190903267136
epoch: 250 || train loss: 0.07448196411132812 || test loss: 0.0749717503786087 || accuracy: 0.982703395259449
epoch: 300 || train loss: 0.0687108188867569 || test loss: 0.06776829063892365 || accuracy: 0.982703395259449
epoch: 350 || train loss: 0.16304448246955872 || test loss: 0.17694440484046936 || accuracy: 0.9461883408071748
epoch: 400 || train loss: 0.0714753195643425 || test loss: 0.07015134394168854 || accuracy: 0.982703395259449
epoch: 450 || train loss: 0.06310828030109406 || test loss: 0.06376880407333374 || accuracy: 0.9852658552210122
epoch: 500 || train loss: 0.07603247463703156 || test loss: 0.06558011472225189 || accuracy: 0.9833440102498399
epoch: 550 || train loss: 0.056692901998758316 || test loss: 0.05807708576321602 || accuracy: 0.9839846252402307
epoch: 600 || train loss: 0.055932581424713135 || test loss: 0.06550461053848267 || accuracy: 0.9839846252402307
epoch: 650 || train loss: 0.05120239779353142 || test loss: 0.05275433883070946 || accuracy: 0.9839846252402307
epoch: 700 || train loss: 0.05041516572237015 || test loss: 0.07151948660612106 || accuracy: 0.9782190903267136
epoch: 750 || train loss: 0.04728306084871292 || test loss: 0.055078983306884766 || accuracy: 0.9852658552210122
epoch: 800 || train loss: 0.04329220578074455 || test loss: 0.04648005589842796 || accuracy: 0.9878283151825753
epoch: 850 || train loss: 0.040871165692806244 || test loss: 0.04408496990799904 || accuracy: 0.9878283151825753
epoch: 900 || train loss: 0.04776952788233757 || test loss: 0.05318393558263779 || accuracy: 0.985906470211403
epoch: 950 || train loss: 0.04114208742976189 || test loss: 0.04988250136375427 || accuracy: 0.9871877001921845
epoch: 1000 || train loss: 0.04607656970620155 || test loss: 0.05340217798948288 || accuracy: 0.9846252402306214